name: CataGens
version: '${project.version}'
main: de.catalysmrl.catagens.CataGens
api-version: 1.18
authors: [ CatalysmRL ]
description: Plugin to create automatic generators

commands:
  catagens:
    description: Main command to manage generators
    usage: /<command>
    aliases: [cg]